<#
===============================================================================
Script: 01_clean_adls_test_outputs.ps1
Purpose:
    Cleans generated test output folders from ADLS Gen2 containers.

Notes:
    - This script is intended for development/test cleanup only.
    - It uses ADLS Gen2 filesystem directory delete for hierarchical namespace.
    - Always preview paths before deleting.
    - Do not use against production data.
===============================================================================
#>

$resourceGroupName = "<RESOURCE_GROUP_NAME>"
$storageAccountName = "<STORAGE_ACCOUNT_NAME>"

# ADLS Gen2 container / filesystem
$fileSystemName = "bronze"

# Example paths generated by the framework.
# Adjust as needed before execution.
$pathsToDelete = @(
    "sqlserver/sales_local/dbo/customers",
    "sqlserver/sales_local/dbo/products",
    "sqlserver/sales_local/dbo/orders",
    "sqlserver/sales_local/dbo/orderitems",
    "sqlserver/sales_local/dbo/payments",
    "files/csv/currency_rates",
    "files/csv/country_currency",
    "files/json/source_system_metadata",
    "files/json/manual_adjustments"
)

Write-Host "Getting storage account key..." -ForegroundColor Cyan

$storageAccountKey = az storage account keys list `
    --resource-group $resourceGroupName `
    --account-name $storageAccountName `
    --query "[0].value" `
    --output tsv

Write-Host "Previewing paths to delete from filesystem: $fileSystemName" -ForegroundColor Yellow

foreach ($path in $pathsToDelete) {
    Write-Host "Candidate path: $fileSystemName/$path" -ForegroundColor Yellow
}

$confirmation = Read-Host "Type DELETE to confirm cleanup"

if ($confirmation -ne "DELETE") {
    Write-Host "Cleanup cancelled." -ForegroundColor Red
    exit
}

foreach ($path in $pathsToDelete) {
    Write-Host "Deleting directory: $fileSystemName/$path" -ForegroundColor Red

    az storage fs directory delete `
        --account-name $storageAccountName `
        --account-key $storageAccountKey `
        --file-system $fileSystemName `
        --name $path `
        --recursive `
        --yes
}

Write-Host "Cleanup completed." -ForegroundColor Cyan